name: zoomslider
channels:
  - conda-forge
  - defaults
packages:
  - jupyter-panel-proxy
dependencies:
  - python=3.11
  - imageio>=2.31.0
  - holoviews>=1.18.0
  - datashader>=0.16.0
  - panel>=1.3.0
  - bokeh>=3.3.0
  - numpy
  - pandas
  - pip
  - pip:
    - colorcet